services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    restart: always
    ports:
      - 5173:80
    networks:
      - steam_reco_app
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules
    command: ["bun", "run", "dev"]
    ports:
      - 3000:3000
    environment:
      # TODO: Set to production in production
      - NODE_ENV=development
    env_file:
      - ./api/.env
    healthcheck:
      test:
        ["CMD", "wget", "--quiet", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
    networks:
      - steam_reco_app

  db:
    restart: unless-stopped
    image: mariadb 
    container_name: db
    env_file:
      - ./db/.env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - steam_reco_app


  api_recommendation:
    container_name: api_recommendation
    build:
      context: ./api_recommendation
      dockerfile: Dockerfile
    volumes:
      - ./api_recommendation:/app
    command:
      [
        "uvicorn",
        "src.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload"
      ]
    # TODO: Remove ports for internal-only access : in production --> remove ports
    ports:
      - 8000:8000
    env_file:
      - ./api_recommendation/.env
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - steam_reco_app

  adminer:
    container_name: adminer
    restart: unless-stopped
    image: adminer
    networks:
      - steam_reco_app
    ports:
      - 8080:8080

volumes:
  api_node_modules:
  db_data:

networks:
  steam_reco_app:
    driver: bridge
