/// Represents a single message within a chatbot conversation.
class ChatMessage {
  /// The role of the message sender (e.g., 'user', 'assistant', 'system').
  final String role;
  
  /// The textual content of the message, supporting Markdown.
  final String content;

  ChatMessage({
    required this.role,
    required this.content,
  });

  /// Returns true if the message was sent by the user.
  bool get isUser => role == 'user';
  
  /// Returns true if the message was generated by the AI assistant.
  bool get isAssistant => role == 'assistant';

  /// Creates a [ChatMessage] instance from a JSON map.
  factory ChatMessage.fromJson(Map<String, dynamic> json) {
    return ChatMessage(
      role: json['role'] as String,
      content: json['content'] as String,
    );
  }

  /// Serializes the message into a JSON map for API requests.
  Map<String, dynamic> toJson() {
    return {
      'role': role,
      'content': content,
    };
  }
}
