name: CI/CD Pipeline

# 1. Quand est-ce que cette usine se lance ?
# -> À chaque fois qu'on pousse du code sur la branche "main"
on:
  push:
    branches:
      - main

jobs:
  build-front:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: 🔑 Connexion au GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Build & Push Front-end (Flutter)
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "API_URL=${{ secrets.API_URL }}" > ./front/.env
          docker build -t ghcr.io/$OWNER/steam-reco-front:latest ./front
          docker push ghcr.io/$OWNER/steam-reco-front:latest

  build-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: 🔑 Connexion au GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Build & Push API (Hono)
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$OWNER/steam-reco-api:latest ./api
          docker push ghcr.io/$OWNER/steam-reco-api:latest

  build-reco:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: 🔑 Connexion au GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Build & Push API Recommendation (FastAPI)
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$OWNER/steam-reco-recommendation:latest ./api_recommendation
          docker push ghcr.io/$OWNER/steam-reco-recommendation:latest

  deploy:
    needs: [build-front, build-api, build-reco]
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: 📄 Copie du fichier docker-compose
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "/home/ubuntu/steam-reco-app/"

      - name: 🚀 Déploiement sur le VPS (via SSH)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/steam-reco-app
            mv docker-compose.prod.yml docker-compose.yml
            docker compose pull
            docker compose up -d
